
### In this code we detect how many direct ES and indirect ES a node is providing

library(emln)#multilayer package
library(readr)
library(ggplot2)
library(cowplot)

setwd("D:/Trabajo/Papers/Norwood_Farm/norwood-ecosystem-services-main_Tinio")


######## -- Create dataframe of edgelist with attributes and ES (AGGREGATED BY LAYERS)

Norwood_farm<-readRDS("Data/Norwood_farm.RData") #read multilayer object
nodes_hab<-Norwood_farm$state_nodes #nodes in each habitat

## Add information of ES per node (values 0-1)

nodes_ES<- right_join(nodes_hab, Norwood_farm$nodes, by = "node_id")%>% 
  select(layer_name,node_id,taxon,"Crop production",
         Pollination, "Crop damage", "Pest control", "Seed dispersal", "Butterfly watching", "Bird watching") %>% 
  group_by(layer_name,node_id) %>% 
  gather("services","value", 4:10) #we conserve species that not directly provide ES because can serve as intermediate hop


## Combine attributes with edge list (to estimate indirect ES)

# upload edgelist
extended_ids_hab<- Norwood_farm$extended_ids %>% select(-layer_to,-weight) %>% 
  mutate(layer_from= case_when(layer_from == '1' ~ 'CP',
                               layer_from == '2' ~ 'GM',
                               layer_from == '3' ~ 'LP',
                               layer_from == '4' ~ 'LU',
                               layer_from == '5' ~ 'MH',
                               layer_from == '6' ~ 'NH',
                               layer_from == '7' ~ 'NL',
                               layer_from == '8' ~ 'PP',
                               layer_from == '9' ~ 'RG',
                               layer_from == '10' ~ 'SF',
                               layer_from == '11' ~ 'WD'))  


# add attributes to the edge list 

#Full list nodes with ES (considering all species and without considering habitat)

list_nodes_ES_provi<-nodes_ES %>% ungroup() %>% select(-layer_name) %>% filter (value ==1) %>% unique #nodes that provide ES
list_nodes_ES_no_provi<- nodes_ES %>% filter(node_id <=87 | node_id >=542) %>% 
  mutate(services = "None", value = 1) %>% ungroup() %>%  select (-layer_name) %>%  unique() # nodes that not provide any ES, ES assigned as None

list_nodes_ES<-rbind(list_nodes_ES_provi,list_nodes_ES_no_provi) #Total list of nodes with ES (with None)


edge_list<- left_join(extended_ids_hab,list_nodes_ES, by = c("node_from"="node_id")) %>% 
   rename("taxon_from"="taxon", "services_from"="services",
                                 "value_from" = "value")%>% 
  left_join(list_nodes_ES, by = c("node_to"="node_id"))  %>% 
  rename("taxon_to"="taxon", "services_to"="services",
         "value_to" = "value") %>% distinct()


## add inverted links (because it is a directed network)

edge_list_inverted<- tibble(values = edge_list$node_to,edge_list$node_from, edge_list$layer_from,
                            edge_list$taxon_to,edge_list$services_to,edge_list$value_to,
                            edge_list$taxon_from,edge_list$services_from,edge_list$value_from)
colnames(edge_list_inverted) <- c("node_from", "node_to", "layer_from", "taxon_from", "services_from",
                                  "value_from", "taxon_to", "services_to", "value_to")

## Combine both data frame to create the final edge list

edgelist_final<- bind_rows(edge_list, edge_list_inverted) %>% rename("layer_name" = "layer_from") 




######## -- Estimate Direct ES (direct ES that each state node provides, which not depends on network structure)

direct_ES <- nodes_ES %>% filter (value ==1) %>% 
  mutate (type = "D") %>% select(-value)



######## -- Estimate Indirect effect of ES 

#### - 1 hop (node - node)

#detect indirect effect from a focal species to ES provided by directly-connected species 

# Create objects to store

layer = c()
services_from = c()
node_from= c()
node_to = c()
taxon_from = c()
services_to = c()

 
# Reorder the dataframe to check indirect interaction in 1 hop
  for (i in 1:nrow(edgelist_final)){
    
    layer  = c(layer, edgelist_final$layer_name[i])
    services_from = c(services_from,edgelist_final$services_from[i])
    node_from = c(node_from,edgelist_final$node_from[i])
    node_to = c(node_to,edgelist_final$node_to[i])
    taxon_from = c(taxon_from, edgelist_final$taxon_from[i])
    services_to = c(services_to, edgelist_final$services_to[i])
   
    
  }


Indirect_1hop<-data.frame(layer,services_from,node_from,node_to,taxon_from,services_to,hop = rep(1, length(layer)), type = rep("I", length(layer))) %>% 
  distinct(node_from, node_to, services_to, .keep_all = TRUE) #each bird and butterfly have three rows per interaction (one per attribute), so we just leave one



#### - 2 hop (node 1 - node 2 - node 3, effect of node 1 on node 3'ES via node 2)
#The code is Ok. We have several indirect effects generated by species interacting with non- crop plants
# and birds.

# Create empty vectors

layer = c()
node_id= c()
node_int = c()
taxon_from = c()
services = c()
node_to = c()
services_to = c()

# Iterate to each row
for (i in 1:nrow(Indirect_1hop)){ #each row represents interaction between species

  j = Indirect_1hop$node_to[i] # check the node_to (intermediate species: node 2 in the title)
  l = Indirect_1hop$layer [i] #check layer of the target species for which we are detecting indirect effects on ES
  
  #we should save the intermediate ES to calculate the output of the indirect ES
  
  # Filter dataframe (filter node 3's ES affected by node 2)
  
  services_int <- Indirect_1hop %>% filter(node_from == j, #filter to show node 2
                                    node_to != Indirect_1hop$node_from[i], #filter to avoid counting the interaction from node 2 to node 1 because the edgelist is directed 
                                    layer == l) %>% select(node_to,services_to)#select node 3 and its ES
  # Storage the results
  
  services_to <- c(services_to, unlist(services_int$services_to)) # add node 3 ES
  node_to <- c(node_to, unlist(services_int$node_to))# add identity of node 3
  node_int <- c(node_int,rep(j, nrow(services_int)))
  node_id <- c(node_id,rep(Indirect_1hop$node_from[i], nrow(services_int)))# add target (node 1) for which we are detected indirect effects 
  taxon_from<- c(taxon_from, rep(Indirect_1hop$taxon_from[i], nrow(services_int)))
  services <- c(services, rep (Indirect_1hop$services_from[i], nrow(services_int)))# direct ES provided by the target node
  layer <- c(layer, rep(l, nrow(services_int)))
  }

Indirect_2hop<- data.frame(layer,node_id,taxon_from,services,node_int,node_to, services_to,type = rep("I", length(services_to)), hop = rep(2,length(services_to)))


#write.csv(Indirect_2hop,"Data/Indirect_2hop.csv")



Indirect_2hop<-read.csv("Data/Indirect_2hop.csv", sep =",",row.names = 1)

#### - Rearrange and create indirect effects of ES 

# 1 hop
Indirect_1hop_m<-Indirect_1hop  %>% rename("services" ="services_from",
                                                               "node_id" = "node_from",
                                                               "taxon" = "taxon_from") %>% 
  mutate(node_int = NA)

Indirect_1hop_m<-Indirect_1hop_m[,c(1,2,3,5,9,4,6,8,7)]

# 2 hop
Indirect_2hop_m<-Indirect_2hop %>% rename("taxon" = "taxon_from") 
Indirect_2hop_m<-Indirect_2hop_m[,c(1,4,2,3,5,6,7,8,9)]

## - Total Indirect effect of ES

I_ES<- rbind(Indirect_1hop_m,Indirect_2hop_m)

#write.csv(I_ES,"Data/Indirect_ES.csv")



######## -- Final dataframe considering direct and indirect effects of ES

D_ES<-direct_ES %>% rename("layer" = "layer_name") %>% mutate(node_to = "-",
                                                              hop = 0, services_to = "-") %>% 
     mutate(node_int = NA)


D_ES<-D_ES[,c(1,4,2,3,9,6,8,5,7)]
D_ES$node_to<-as.integer(D_ES$node_to)

#write.csv(D_ES,"Data/Direct_ES_hab.csv", row.names= FALSE)

Final_ES<-rbind(D_ES,I_ES)

#write.csv(Final_ES,"Data/Final_ES.csv", row.names= FALSE)




########## -- Create dataframe of edgelist with attributes and ES (AGGREGATED BY LAYERS)

Norwood_farm<-readRDS("Data/Norwood_farm.RData") #read multilayer object
nodes_hab<-Norwood_farm$state_nodes #nodes in each habitat
  nodes_hab<- nodes_hab %>% select(-layer_id, -layer_name) %>% unique()
## Add information of ES per node (values 0-1)

nodes_ES<- right_join(nodes_hab, Norwood_farm$nodes, by = "node_id")%>% 
  select(node_id,taxon,"Crop production",
         Pollination, "Crop damage", "Pest control", "Seed dispersal", "Butterfly watching", "Bird watching") %>% 
 unique() %>% 
  gather("services","value", 3:9) #we conserve species that not directly provide ES because can serve as intermediate hop


## Combine attributes with edge list (to estimate indirect ES)

# upload edgelist
extended_ids_hab<- Norwood_farm$extended_ids %>% select(-layer_from,-layer_to,-weight) 

# add attributes to the edge list 

#Full list nodes with ES (considering all species and without considering habitat)

list_nodes_ES_provi<-nodes_ES %>% filter (value ==1) %>% unique #nodes that provide ES
list_nodes_ES_no_provi<- nodes_ES %>% filter(node_id <=87 | node_id >=542) %>% 
  mutate(services = "None", value = 1) %>% ungroup() %>%  unique() # nodes that not provide any ES, ES assigned as None

list_nodes_ES<-rbind(list_nodes_ES_provi,list_nodes_ES_no_provi) #Total list of nodes with ES (with None)


edge_list<- left_join(extended_ids_hab,list_nodes_ES, by = c("node_from"="node_id")) %>% 
  rename("taxon_from"="taxon", "services_from"="services",
         "value_from" = "value")%>% 
  left_join(list_nodes_ES, by = c("node_to"="node_id"))  %>% 
  rename("taxon_to"="taxon", "services_to"="services",
         "value_to" = "value") %>% distinct()


## add inverted links (because it is a directed network)

edge_list_inverted<- tibble(values = edge_list$node_to,edge_list$node_from,
                            edge_list$taxon_to,edge_list$services_to,edge_list$value_to,
                            edge_list$taxon_from,edge_list$services_from,edge_list$value_from)
colnames(edge_list_inverted) <- c("node_from", "node_to", "taxon_from", "services_from",
                                  "value_from", "taxon_to", "services_to", "value_to")

## Combine both data frame to create the final edge list

edgelist_final<- bind_rows(edge_list, edge_list_inverted) 




######## -- Estimate Direct ES (AGGREAGTED - direct ES that each state node provides, which not depends on network structure)

direct_ES_agg <- nodes_ES %>% filter (value ==1) %>% 
  mutate (type = "D") %>% select(-value)




######## -- Estimate Indirect effect of ES (AGGREGATED)

#### - 1 hop (node - node)

#detect indirect effect from a focal species to ES provided by directly-connected species 

# Create objects to store

layer = c()
services_from = c()
node_from= c()
node_to = c()
taxon_from = c()
services_to = c()


# Reorder the dataframe to check indirect interaction in 1 hop
for (i in 1:nrow(edgelist_final)){
  
  services_from = c(services_from,edgelist_final$services_from[i])
  node_from = c(node_from,edgelist_final$node_from[i])
  node_to = c(node_to,edgelist_final$node_to[i])
  taxon_from = c(taxon_from, edgelist_final$taxon_from[i])
  services_to = c(services_to, edgelist_final$services_to[i])
  
  
}


Indirect_1hop_agg<-data.frame(layer = rep ("Aggr", length(services_from)),services_from,node_from,node_to,taxon_from,services_to,hop = rep(1, length(services_from)), type = rep("I", length(services_from))) %>% 
  distinct(node_from, node_to, services_to, .keep_all = TRUE) #each bird and butterfly have three rows per interaction (one per attribute), so we just leave one


#### - 2 hop (node 1 - node 2 - node 3, effect of node 1 on node 3'ES via node 2)
#The code is Ok. We have several indirect effects generated by species interacting with non- crop plants
# and birds.

# Create empty vectors

node_id= c()
node_int = c()
taxon_from = c()
services = c()
node_to = c()
services_to = c()

# Iterate to each row
for (i in 1:nrow(Indirect_1hop_agg)){ #each row represents interaction between species
  
  j = Indirect_1hop_agg$node_to[i] # check the node_to (intermediate species: node 2 in the title)
 
  
  # Filter dataframe (filter node 3's ES affected by node 2)
  
  services_int <- Indirect_1hop_agg %>% filter(node_from == j, #filter to show node 2
                                           node_to != Indirect_1hop_agg$node_from[i])%>% #filter to avoid counting the interaction from node 2 to node 1 because the edgelist is directed 
                                             select(node_to,services_to)#select node 3 and its ES
  # Storage the results
  
  services_to <- c(services_to, unlist(services_int$services_to)) # add node 3 ES
  node_int <- c(node_int, rep(j, nrow(services_int))) # add node 2 intermediate
  node_to <- c(node_to, unlist(services_int$node_to))# add identity of node 3
  node_id <- c(node_id,rep(Indirect_1hop_agg$node_from[i], nrow(services_int)))# add target (node 1) for which we are detected indirect effects 
  taxon_from<- c(taxon_from, rep(Indirect_1hop_agg$taxon_from[i], nrow(services_int)))
  services <- c(services, rep (Indirect_1hop_agg$services_from[i], nrow(services_int)))# direct ES provided by the target node
  
}

Indirect_2hop_agg<- data.frame(layer = rep ("Aggr", length(node_id)),node_id,taxon_from,services,node_int,node_to, services_to,type = rep("I", length(services_to)), hop = rep(2,length(services_to)))



#### - Rearrange and joint with indirect effects in habitats to create final data frame

# 1 hop
Indirect_1hop_agg_m<-Indirect_1hop_agg  %>% rename("services" ="services_from",
                                           "node_id" = "node_from",
                                           "taxon" = "taxon_from")%>% 
  mutate(node_int = NA)


Indirect_1hop_agg_m<-Indirect_1hop_agg_m[,c(1,2,3,5,9,4,6,8,7)]

# 2 hop
Indirect_2hop_agg_m<-Indirect_2hop_agg %>% rename("taxon" = "taxon_from") 
Indirect_2hop_agg_m<-Indirect_2hop_agg_m[,c(1,4,2,3,5,6,7,8,9)]


## - Total Indirect effect of ES

I_ES_agg<- rbind(Indirect_1hop_agg_m,Indirect_2hop_agg_m)


#Joint with not aggregated dataframe
I_ES_hab<-read.csv("Data/Indirect_ES.csv", sep =",",row.names = 1)

I_ES_final<-rbind(I_ES_hab,I_ES_agg)#including both aggreated and not aggregated version

#write.csv(I_ES_final,"Data/Final_I_ES.csv", row.names= FALSE)

######## -- Final dataframe of direct effect including aggregated and not aggregated habitats

D_ES_agg<-direct_ES_agg %>% mutate(layer = "Aggr", node_to = "-",
                                                              hop = 0, services_to = "-") %>% 
        mutate(node_int = NA)


D_ES<-D_ES_agg[,c(5,3,1,2,9,6,8,4,7)]
D_ES$node_to<-as.integer(D_ES$node_to)

D_ES_hab<-read.csv("Data/Direct_ES_hab.csv", sep =",") #upload direct effects per habitat
Final_D_ES<-rbind(D_ES_hab,D_ES)

#write.csv(Final_D_ES,"Data/Final_D_ES.csv", row.names= FALSE)


######## -- Final dataframe of D and I effects including aggregated and not aggregated habitats

Final_ES<-rbind(Final_D_ES,I_ES_final)


#write.csv(Final_ES,"Data/Final_ES.csv", row.names= FALSE)



######### ESTIMATE OUTPUT OF DIRECT AND INDIRECT EFFECTS ON ES ######
# For each interaction we assigned the following outputs:
# + (provide ES, increase ES or decrease crop damage)
# - (provide EDS (crop damage), decrease ES provision or increase crop damage)



############ Direct effects ---

direct <- read.csv("Data/Final_ES.csv", sep =",") %>% filter(type == "D")

output_ES_direct <- direct %>%  mutate (output = ifelse(services == "Crop damage", "-", "+")) 



############ Indirect effects  ---

# Define vector of trophic groups to state the conditions

plants = 1:87
crops = 88:93
flow_vis = 94:334
aphid = 335:362
pri_par = 363:373
sec_par = 374:380
leaf_par = 381:473
seed_ins = 474:492
seed_bird = 493:504
seed_rod = 505:508
butt = 509:524
seed_ins_par = 525:541
rod_par = 542:549



######### 1 HOP -- 

hop_1 <- read.csv("Data/Final_ES.csv", sep =",") %>% filter(hop == 1 & type == "I", services_to !="None") #remove indirect effect that not affect any ES


# We assigned the indirect output according to node_id and node_to

output_ES_1hop<- hop_1 %>%  
  mutate(output = case_when(
    (node_id %in% aphid| node_id %in% seed_bird | node_id %in% seed_ins |
    node_id %in% seed_rod) & services_to == "Crop production"  ~ "-", #aphids, birds, rodents, seed inds reduce crop production
    
    node_id %in% plants & node_to %in% seed_bird & services_to == "Crop damage" ~ "-",#plants--->+birds--->+seed predation
    
    node_id %in% plants & (node_to %in% aphid| node_to %in% seed_bird | node_to %in% seed_ins |
      node_to %in% seed_rod) & services_to == "Crop production"  ~ "-", #plants that increase birds, rodents, insects, aphids population, increase crop damage
   
     node_id %in% crops & (node_to %in% aphid| node_to %in% seed_bird | node_to %in% seed_ins |
      node_to %in% seed_rod) & services_to == "Crop production"  ~ "-", #same for crops
    
    node_id %in% aphid & services_to == "Pest control" ~ "+", #aphids eat plants and crops inceasing their abundances and increasing the resource for pest control sps
    
    
      (node_id %in% plants |  node_id %in% crops)  &   
      (services_to == "Seed dispersal" | services_to == "Bird watching") ~ "+", #plants and crops increase population of birds and hence SD and bird watching
  
    (node_id %in% plants |  node_id %in% crops)  &   
      services_to == "Crop damage" ~ "-", #plants and crops increase the population of birds, aphids, rodents and insects  and hence the crop damage
    
    TRUE ~ "+"
  ))
   


######### 2 HOPS -- 

hop_2 <- read.csv("Data/Final_ES.csv", sep =",") %>% filter(hop == 2 & type == "I", services_to !="None") #remove indirect effect that not affect any ES


# We assigned the indirect output according from "node_id" to "node_to" via "node_int"

output_ES_2hops<- hop_2 %>%  
  mutate(output = case_when( 
    
    (node_id %in% plants | node_id %in% crops) &  (node_int%in%aphid | node_int%in%seed_ins) &
      services_to == "Pest control"  ~ "+",    #plants,crops --> +aphids,ins -->+parasitoides -->+ pestcontrol
    
    
    (node_id %in% plants | node_id %in% crops) &  (node_int%in%aphid | node_int%in%seed_bird| 
    node_int%in%seed_ins | node_int%in%seed_rod) &
    services_to == "Crop production"  ~ "-",     #plants,crops --> + seed predators --> - crop --> - crop production
  
    
    (node_id %in% plants | node_id %in% crops) &  (node_int%in%flow_vis | node_int%in%pri_par|
    node_int%in%sec_par | node_int%in%leaf_par | node_int%in%butt |  node_int%in%rod_par |
     node_int%in%seed_ins_par) & services_to == "Crop production" ~ "+",      #plants,crops --> + seed predators par  or poll--> + crop --> + crop production
    
    
    (node_id %in% plants | node_id %in% crops) &  (node_int%in%pri_par| node_int%in%sec_par |
    node_int%in%leaf_par |   node_int%in%rod_par |  node_int%in%seed_ins_par) &
      (services_to == "Crop damage")  ~ "+",      # plants, crops --> + parasitoides --> - herbuvires and seed predators crop damage (es un efecto +)
    
    
    (node_id%in%aphid | node_id%in%seed_bird| node_id%in%seed_ins |node_id%in%seed_rod) &
    (node_int%in%pri_par| node_int%in%sec_par |node_int%in%leaf_par | node_int%in%rod_par |
     node_int%in%seed_ins_par) & (services_to == "Crop production" | 
    services_to == "Crop damage") ~ "+",      #seed predators--> + pop. parasitoides --> - seed predators -> - crop damage and + crop productio
    

    (node_id%in%flow_vis | node_id%in%butt) & (node_int%in%plants| node_int%in%crops) &
      (services_to == "Pollination" | services_to == "Seed dispersal" | services_to == "Butterfly watching"| 
         services_to == "Bird watching"| services_to == "Pest control") ~ "+", # flower visitors and butt --> + plants,crops--> + pop, pollinators, parasitoides, birds --> + poll, pest control, seed disp and bird watching
    
    
    (node_id%in%flow_vis | node_id%in%butt) & (node_int%in%plants| node_int%in%crops) &
      (services_to == "Crop damage")  ~ "-", # flower visitors and butt --> + plants,crops--> + pop seed predators --> + crop damage 
   
    
    (node_id%in%aphid | node_id%in%seed_bird| node_id%in%seed_ins |node_id%in%seed_rod) &
    (node_int%in%plants| node_int%in%crops) & (services_to == "Pollination" | 
    services_to == "Butterfly watching"| services_to == "Bird watching"| services_to == "Pest control"| 
    services_to == "Seed dispersal") ~ "-",     # seed predators --> - pop crops --> - pop birds, flower vis, parasitodes --> - pest control, watching, pollination
    
    (node_id%in%aphid | node_id%in%seed_bird| node_id%in%seed_ins |node_id%in%seed_rod) &
      (node_int%in%plants| node_int%in%crops) & (services_to == "Crop damage") ~ "+",     # seed predators --> - pop crops --> - pop seed predators --> - crop damage (+)
    
    
    (node_id%in%pri_par| node_id%in%sec_par |node_id%in%leaf_par |node_int%in%rod_par |
      node_id%in%seed_ins_par) & (node_int%in%plants| node_int%in%crops) & 
      (services_to == "Pollination" | services_to == "Butterfly watching"|
       services_to == "Bird watching"| services_to == "Pest control"| 
      services_to == "Seed dispersal") ~ "+",    # par --> + pop plants --> + pop birds, flower vis, par --> + pest control, poll, bird and butt watching
    
    
    (node_id%in%pri_par| node_id%in%sec_par |node_id%in%leaf_par |node_int%in%rod_par |
       node_int%in%seed_ins_par) & (node_int%in%plants| node_int%in%crops) & 
      (services_to == "Crop damage") ~ "-",  # par --> + pop plants --> + crop damage (-)
    
    
    (node_id%in%pri_par| node_id%in%sec_par |node_id%in%leaf_par |node_int%in%rod_par |
       node_id%in%seed_ins_par) & (node_int%in%aphid | node_int%in%seed_bird| 
      node_int%in%seed_ins | node_int%in%seed_rod) &
      services_to == "Crop production" ~ "+", # par --> + pop seed predators --> + pop crops --> + crop production
    
    
    (node_id%in%pri_par| node_id%in%sec_par |node_id%in%leaf_par |node_int%in%rod_par |
       node_id%in%seed_ins_par) & (node_int%in%aphid | node_int%in%seed_bird| 
       node_int%in%seed_ins | node_int%in%seed_rod) &
      services_to == "Pest control" ~ "-" # par --> + pop seed predators --> + pop parasitoide --> - pest control
    
     ))


#check<-output_ES_2hops %>%  filter(is.na(output)) #check for NA in output column



############ Final dataframe output of direct and indirect effects  ---


output_ES<-rbind(output_ES_direct,output_ES_1hop,output_ES_2hops)

#write.csv(output_ES,"Data/output_ES.csv", row.names= FALSE)




######## -- Plots (put at the end of the script later)

output_ES<-read.csv ("Data/output_ES.csv", sep =",")

## Proportion of + and - outputs per habitat

# direct
Prop_output<- output_ES %>% filter(type == "D") %>%  group_by(layer, output) %>% 
  summarize(count= n()) %>% group_by(layer) %>% mutate(tot =sum(count)) %>% 
  group_by(layer,output) %>% summarize(prop = count/tot)


Hab_ES_output_dir<-Prop_output%>% 
  ggplot(aes(y=prop, x=layer, fill =output)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Direct")+
  labs(x='Habitat', y="Prop ES provided") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=15, color='black'),
        axis.text.x= element_text(size =13, angle = 90), 
        axis.title = element_text(size=17, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_text(size = 13, color = "black"),
        legend.text = element_text(size = 11),
        legend.position = "bottom")


# indirect
Prop_output_ind<- output_ES %>% filter(type == "I") %>%  group_by(layer, output) %>% 
  summarize(count= n()) %>% group_by(layer) %>% mutate(tot =sum(count)) %>% 
  group_by(layer,output) %>% summarize(prop = count/tot)


Hab_ES_output_ind<-Prop_output_ind%>% 
  ggplot(aes(y=prop, x=layer, fill =output)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Indirect (2 hops)")+
  labs(x='Habitat', y="Prop ES provided") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=15, color='black'),
        axis.text.x= element_text(size =13, angle = 90), 
        axis.title = element_text(size=17, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_text(size = 13, color = "black"),
        legend.text = element_text(size = 11),
        legend.position = "bottom")


upper_row<- plot_grid(Hab_ES_output_dir ,
                      Hab_ES_output_ind , 
                      ncol = 2)
upper_row


### -  Prop of output according to taxon /habitat 


## - direct

taxon_ES_output_dir<-output_ES %>% filter (type == "D") %>% group_by(layer, output)  %>% 
  mutate(Total = n()) %>% group_by(layer,output, taxon) %>% 
  summarize( Number = n(), Prop = Number /Total) %>% unique()

#positive
taxon_ES_output_pos_dir <-taxon_ES_output_dir %>% filter(output =="+") %>% 
  ggplot(aes(y=Prop, x=layer, fill = taxon)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Positive - Direct")+
  labs(x='Habitat', y="Prop ES provided per taxon") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90), 
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 5),
        legend.position = "bottom",
        legend.key.size = unit(0.7,"line"))


#negative
taxon_ES_output_neg_dir <-taxon_ES_output_dir %>% filter(output =="-") %>% 
  ggplot(aes(y=Prop, x=layer, fill = taxon)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Negative - Direct")+
  labs(x='Habitat', y="Prop ES provided per taxon") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90), 
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 5),
        legend.position = "bottom",
        legend.key.size = unit(0.7,"line"))


upper_row<- plot_grid(taxon_ES_output_pos_dir ,
                      taxon_ES_output_neg_dir , 
                      ncol = 2)
upper_row



## - indirect

taxon_ES_output_ind<-output_ES %>% filter (type == "I") %>% group_by(layer, output)  %>% 
  mutate(Total = n()) %>% group_by(layer,output, taxon) %>% 
  summarize( Number = n(), Prop = Number /Total) %>% unique()

#positive
taxon_ES_output_pos_ind <-taxon_ES_output_ind %>% filter(output =="+") %>% 
  ggplot(aes(y=Prop, x=layer, fill = taxon)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Positive - Indirect")+
  labs(x='Habitat', y="Prop ES provided per taxon") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90), 
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 5),
        legend.position = "bottom",
        legend.key.size = unit(0.7,"line"))


#negative
taxon_ES_output_neg_ind <-taxon_ES_output_ind %>% filter(output =="-") %>% 
  ggplot(aes(y=Prop, x=layer, fill = taxon)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Negative - Indirect")+
  labs(x='Habitat', y="Prop ES provided per taxon") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90), 
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 5),
        legend.position = "bottom",
        legend.key.size = unit(0.7,"line"))


upper_row<- plot_grid(taxon_ES_output_pos_ind ,
                      taxon_ES_output_neg_ind , 
                      ncol = 2)
upper_row















###################### Data exploration ######
library(cowplot)

Final_ES <- read.csv("Data/Final_ES.csv", sep =",")


## Direct and indirect ES provided in each habitat and in total (aggregated network) (1 and 2 hops)

 ##Number 

#1 hop
Hab_ES<-Final_ES %>% group_by(layer, type) %>% filter( hop == 0 | hop == 1,
                                                       services_to != "None") %>%
  summarize(count = n())


Hab_ES_1<-Hab_ES%>% 
  ggplot(aes(y=count, x=layer, fill =type)) + 
  geom_bar(position="dodge", stat="identity")+
  labs(x='Habitat', y="Number of ES provided") +theme_bw()+ggtitle("1 hop")+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=15, color='black'),
        axis.text.x= element_text(size =13, angle = 90), 
        axis.title = element_text(size=17, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_text(size = 13, color = "black"),
        legend.text = element_text(size = 11),
        legend.position = "bottom")

#2 hop
Hab_ES_2<-Final_ES %>% group_by(layer, type) %>% filter(services_to != "None") %>%
  summarize(count = n())


Hab_ES_2<-Hab_ES_2%>% 
  ggplot(aes(y=count, x=layer, fill =type)) + 
  geom_bar(position="dodge", stat="identity")+
  labs(x='Habitat', y="Number of ES provided") +theme_bw()+
  ggtitle("2 hops")+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=15, color='black'),
        axis.text.x= element_text(size =13, angle = 90), 
        axis.title = element_text(size=17, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_text(size = 13, color = "black"),
        legend.text = element_text(size = 11),
        legend.position = "bottom")

upper_row<- plot_grid(Hab_ES_1 ,
                      Hab_ES_2 , 
                      ncol = 2)
upper_row


## Proportion

#1 hop
Hab_ES_prop<-Final_ES %>% group_by(layer, type) %>% filter( hop == 0 | hop == 1,
                                                       services_to != "None") %>%
  summarize(count= n()) %>% group_by(layer) %>% mutate(tot =sum(count)) %>% 
  group_by(layer,type) %>% summarize(prop = count/tot)


Hab_ES_1<-Hab_ES_prop%>% 
  ggplot(aes(y=prop, x=layer, fill =type)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("1 hop")+
  labs(x='Habitat', y="Prop ES provided") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=15, color='black'),
        axis.text.x= element_text(size =13, angle = 90), 
        axis.title = element_text(size=17, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_text(size = 13, color = "black"),
        legend.text = element_text(size = 11),
        legend.position = "bottom")

 
#2 hops
Hab_ES_prop_2<-Final_ES %>% group_by(layer, type) %>% filter(services_to != "None") %>%
  summarize(count= n()) %>% group_by(layer) %>% mutate(tot =sum(count)) %>% 
  group_by(layer,type) %>% summarize(prop = count/tot)


Hab_ES_2<-Hab_ES_prop_2 %>% 
  ggplot(aes(y=prop, x=layer, fill =type)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("2 hops")+
  labs(x='Habitat', y="Prop ES provided") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=15, color='black'),
        axis.text.x= element_text(size =13, angle = 90), 
        axis.title = element_text(size=17, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_text(size = 13, color = "black"),
        legend.text = element_text(size = 11),
        legend.position = "bottom")
 

upper_row<- plot_grid(Hab_ES_1 ,
                      Hab_ES_2 , 
                      ncol = 2)
upper_row
 
 
 


 
 ## Prop of direct and Indirect ES provided per taxon /habitat 
 
# 1 hop

taxon_ES_1<-Final_ES %>% group_by(layer, type) %>% filter(services_to != "None", hop == 0 | hop ==1) %>% 
  mutate(Total = n()) %>% group_by(layer,type, taxon) %>% 
  summarize( Number = n(), Prop = Number /Total) %>% unique()

#Direct
D_taxon_ES_1<-taxon_ES_1 %>% filter(type == "D") %>% 
  ggplot(aes(y=Prop, x=layer, fill = taxon)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Direct ES - 1 hop")+
  labs(x='Habitat', y="Prop ES provided per taxon") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90), 
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 5),
        legend.position = "bottom",
        legend.key.size = unit(0.7,"line"))

#Indirect
I_taxon_ES_1<-taxon_ES_1 %>% filter(type == "I") %>% 
  ggplot(aes(y=Prop, x=layer, fill = taxon)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Indirect ES - 1 hop")+
  labs(x='Habitat', y="Prop ES provided per taxon") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90),
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 5),
        legend.position = "bottom",
        legend.key.size = unit(0.7,"line"))



upper_row<- plot_grid(D_taxon_ES_1 ,
                      I_taxon_ES_1 , 
                      ncol = 2)

#2 hops

taxon_ES_2<-Final_ES %>% group_by(layer, type) %>% filter(services_to != "None") %>% 
  mutate(Total = n()) %>% group_by(layer,type, taxon) %>% 
  summarize( Number = n(), Prop = Number /Total) %>% unique()

#Direct
D_taxon_ES_2<-taxon_ES_2 %>% filter(type == "D") %>% 
  ggplot(aes(y=Prop, x=layer, fill = taxon)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Direct ES - 2 hops")+
  labs(x='Habitat', y="Prop ES provided per taxon") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90), 
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 5),
        legend.position = "bottom",
        legend.key.size = unit(0.7,"line"))

#Indirect
I_taxon_ES_2<-taxon_ES_2 %>% filter(type == "I") %>% 
  ggplot(aes(y=Prop, x=layer, fill = taxon)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Indirect ES - 2 hops")+
  labs(x='Habitat', y="Prop ES provided per taxon") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90),
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 5),
        legend.position = "bottom",
        legend.key.size = unit(0.7,"line"))



upper_row<- plot_grid(D_taxon_ES_2 ,
                      I_taxon_ES_2 , 
                      ncol = 2)





 
 ## Prop of direct and Indirect ES provided per services /habitat 

# 1 hop
services_ES_1<-Final_ES %>% group_by(layer, type) %>% filter(services_to != "None" , hop == 0 | hop == 1) %>% 
  mutate(Total = n()) %>% group_by(layer,type, services) %>% 
  summarize( Number = n(), Prop = Number /Total) %>% unique()


#Direct
D_services_ES_1<-services_ES_1 %>% filter(type == "D") %>% 
  ggplot(aes(y=Prop, x=layer, fill = services)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Direct ES - 1 hop")+
  labs(x='Habitat', y="Prop of ES provided per type") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90),
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 4),
        legend.position = "bottom")



#Indirect
I_services_ES_1<-services_ES_1 %>% filter(type == "I") %>% 
  ggplot(aes(y=Prop, x=layer, fill = services)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Indirect ES - 1 hop")+
  labs(x='Habitat', y="Prop of ES provided per type") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90),
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 4),
        legend.position = "bottom")



upper_row<- plot_grid(D_services_ES_1 ,
                      I_services_ES_1 , 
                      ncol = 2)


# 2 hops
services_ES_2<-Final_ES %>% group_by(layer, type) %>% filter(services_to != "None") %>% 
  mutate(Total = n()) %>% group_by(layer,type, services) %>% 
  summarize( Number = n(), Prop = Number /Total) %>% unique()


#Direct
D_services_ES_2<-services_ES_2 %>% filter(type == "D") %>% 
  ggplot(aes(y=Prop, x=layer, fill = services)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Direct ES - 2 hops")+
  labs(x='Habitat', y="Prop of ES provided per type") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90),
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 4),
        legend.position = "bottom")



#Indirect
I_services_ES_2<-services_ES_2 %>% filter(type == "I") %>% 
  ggplot(aes(y=Prop, x=layer, fill = services)) + 
  geom_bar(position="stack", stat="identity")+ ggtitle("Indirect ES - 2 hops")+
  labs(x='Habitat', y="Prop of ES provided per type") +theme_bw()+
  theme_classic()+
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",fill = NA,size = 1),
        panel.spacing = unit(0.5, "cm", data = NULL),
        axis.text = element_text(size=13, color='black'),
        axis.text.x= element_text(size =11, angle = 90), 
        axis.text.y= element_text(size =11, angle = 90),
        axis.title = element_text(size=15, color='black'),
        axis.line = element_blank(),
        legend.text.align = 0,
        legend.title =  element_blank(),
        legend.text = element_text(size = 4),
        legend.position = "bottom")



upper_row<- plot_grid(D_services_ES_2 ,
                      I_services_ES_2 , 
                      ncol = 2)




 
 ## Bar plot of species and the total number of direct and indirect ES
 
# 1 hop

sps_imp_1<-Final_ES %>% group_by(layer, type) %>% filter(services_to != "None" , hop == 0 | hop ==1) %>% 
  mutate(Total = n()) %>% group_by(layer,type, node_id) %>% 
  summarize( Number = n(), Prop = Number /Total) %>% unique()





sps_imp<-Final_ES %>% group_by(layer, type) %>% filter(services_to != "None") %>% 
  mutate(Total = n()) %>% group_by(layer,type, node_id) %>% 
  summarize( Number = n(), Prop = Number /Total) %>% unique()


sps_imp_tot<- Final_ES %>% group_by(type) %>% filter(services_to != "None") %>% 
  mutate(Total = n()) %>% group_by(type, node_id) %>% 
  summarize( layer= "Tot",Number = n(), Prop = Number /Total) %>% unique()
sps_imp_tot<-sps_imp_tot[,c(3,1,2,4,5)]

sps_imp_tot_ES<-rbind(sps_imp_tot,sps_imp) %>% group_by(layer,node_id) %>% 
  summarize(Tot = sum(Number)) #considering both direct and indirect

 

#Just Total (without considering habitats)
 sps_imp_number<- sps_imp_tot_ES %>% filter(layer == "Tot") %>%
   ggplot(aes(y=Tot, x= node_id)) + geom_bar(stat="identity")+
   labs(x='Node_id', y="Number of ES provided") +theme_bw()+
   theme_classic()+
   theme(panel.grid = element_blank(),
         panel.border = element_rect(color = "black",fill = NA,size = 1),
         panel.spacing = unit(0.5, "cm", data = NULL),
         axis.text = element_text(size=15, color='black'),
         axis.text.x= element_text(size =13, angle = 90), 
         axis.title = element_text(size=17, color='black'),
         axis.line = element_blank(),
         legend.text.align = 0,
         legend.title =  element_text(size = 13, color = "black"),
         legend.text = element_text(size = 11))
 
 sps_imp_number
 
 #chose the four species that provide ecosystem services the most
 
 four_sp<-sps_imp_tot_ES %>% filter(layer == "Tot") %>% 
   arrange(desc(Tot)) %>% head(n = 4)
 
 four_sp_birds<-sps_imp_tot_ES %>% filter(layer != "Tot", node_id == 495 | node_id == 496 |
                                          node_id == 497 | node_id ==502) 
 four_sp_birds$node_id<-as.character(four_sp_birds$node_id)
 
 #Most important nodes across habitat
 
 imp_sps_ES<- four_sp_birds %>%
   ggplot(aes(y=Tot, x= node_id, fill = layer)) + geom_bar(position="dodge", stat="identity")+
   labs(x='Node_id', y="Number of ES provided") +theme_bw()+
   theme_classic()+
   theme(panel.grid = element_blank(),
         panel.border = element_rect(color = "black",fill = NA,size = 1),
         panel.spacing = unit(0.5, "cm", data = NULL),
         axis.text = element_text(size=15, color='black'),
         axis.text.x= element_text(size =13, angle = 90), 
         axis.title = element_text(size=17, color='black'),
         axis.line = element_blank(),
         legend.text.align = 0,
         legend.title =  element_text(size = 13, color = "black"),
         legend.text = element_text(size = 11))
 
 imp_sps_ES
 
 
 
 
 
 ##################### 1 HOP
 
 
 ## Prop of direct and Indirect ES provided per taxon /habitat (1 hop)
 
 taxon_ES_1<-Final_ES %>% group_by(layer, type) %>% filter(services_to != "None", hop == 0 | hop == 1) %>% 
   mutate(Total = n()) %>% group_by(layer,type, taxon) %>% 
   summarize( Number = n(), Prop = Number /Total) %>% unique()
 


 taxon_tot_1<- Final_ES %>% group_by(type) %>% filter(services_to != "None",  hop == 0 | hop == 1) %>% 
   mutate(Total = n()) %>% group_by(type, taxon) %>% 
   summarize( layer= "Tot",Number = n(), Prop = Number /Total) %>% unique()
 taxon_tot_1<-taxon_tot_1[,c(3,1,2,4,5)]
 
 taxon_ES_1<-rbind(taxon_tot_1,taxon_ES_1)
 
 #Direct
 D_taxon_ES_1<-taxon_ES_1 %>% filter(type == "D") %>% 
   ggplot(aes(y=Prop, x=layer, fill = taxon)) + 
   geom_bar(position="stack", stat="identity")+ ggtitle("Direct ES")+
   labs(x='Habitat', y="Prop ES provided per taxon") +theme_bw()+
   theme_classic()+
   theme(panel.grid = element_blank(),
         panel.border = element_rect(color = "black",fill = NA,size = 1),
         panel.spacing = unit(0.5, "cm", data = NULL),
         axis.text = element_text(size=15, color='black'),
         axis.text.x= element_text(size =13, angle = 90), 
         axis.title = element_text(size=17, color='black'),
         axis.line = element_blank(),
         legend.text.align = 0,
         legend.title =  element_text(size = 13, color = "black"),
         legend.text = element_text(size = 11))
 
 D_taxon_ES_1
 
 #Indirect
 I_taxon_ES_1<-taxon_ES_1 %>% filter(type == "I") %>% 
   ggplot(aes(y=Prop, x=layer, fill = taxon)) + 
   geom_bar(position="stack", stat="identity")+ ggtitle("Indirect ES")+
   labs(x='Habitat', y="Prop ES provided per taxon") +theme_bw()+
   theme_classic()+
   theme(panel.grid = element_blank(),
         panel.border = element_rect(color = "black",fill = NA,size = 1),
         panel.spacing = unit(0.5, "cm", data = NULL),
         axis.text = element_text(size=15, color='black'),
         axis.text.x= element_text(size =13, angle = 90), 
         axis.title = element_text(size=17, color='black'),
         axis.line = element_blank(),
         legend.text.align = 0,
         legend.title =  element_text(size = 13, color = "black"),
         legend.text = element_text(size = 11))
 
 I_taxon_ES_1
 
 
 
 
 
 ## Prop of direct and Indirect ES provided per services /habitat (1 hop)
 
 services_ES_1<-Final_ES %>% group_by(layer, type) %>% filter(services_to != "None" , hop == 0 | 1) %>% 
   mutate(Total = n()) %>% group_by(layer,type, services) %>% 
   summarize( Number = n(), Prop = Number /Total) %>% unique()
 
 
 services_tot_1<- Final_ES %>% group_by(type) %>% filter(services_to != "None", hop == 0 | 1) %>% 
   mutate(Total = n()) %>% group_by(type, services) %>% 
   summarize( layer= "Tot",Number = n(), Prop = Number /Total) %>% unique()
 services_tot_1<-services_tot_1[,c(3,1,2,4,5)]
 
 services_tot_ES_1<-rbind(services_tot_1,services_ES_1)
 
 #Direct
 D_services_ES_1<-services_tot_ES_1 %>% filter(type == "D") %>% 
   ggplot(aes(y=Prop, x=layer, fill = services)) + 
   geom_bar(position="stack", stat="identity")+ ggtitle("Direct ES")+
   labs(x='Habitat', y="Prop of ES provided per type") +theme_bw()+
   theme_classic()+
   theme(panel.grid = element_blank(),
         panel.border = element_rect(color = "black",fill = NA,size = 1),
         panel.spacing = unit(0.5, "cm", data = NULL),
         axis.text = element_text(size=15, color='black'),
         axis.text.x= element_text(size =13, angle = 90), 
         axis.title = element_text(size=17, color='black'),
         axis.line = element_blank(),
         legend.text.align = 0,
         legend.title =  element_text(size = 13, color = "black"),
         legend.text = element_text(size = 11))
 
 D_services_ES_1
 
 #Indirect
 I_services_ES_1<-services_tot_ES_1 %>% filter(type == "I") %>% 
   ggplot(aes(y=Prop, x=layer, fill = services)) + 
   geom_bar(position="stack", stat="identity")+ ggtitle("Indirect ES")+
   labs(x='Habitat', y="Prop of ES provided per type") +theme_bw()+
   theme_classic()+
   theme(panel.grid = element_blank(),
         panel.border = element_rect(color = "black",fill = NA,size = 1),
         panel.spacing = unit(0.5, "cm", data = NULL),
         axis.text = element_text(size=15, color='black'),
         axis.text.x= element_text(size =13, angle = 90), 
         axis.title = element_text(size=17, color='black'),
         axis.line = element_blank(),
         legend.text.align = 0,
         legend.title =  element_text(size = 13, color = "black"),
         legend.text = element_text(size = 11))
 
 I_services_ES_1
 
 
 
 
 ## Bar plot of species and the total number of direct and indirect ES (1 hop)
 
 sps_imp_1<-Final_ES %>% group_by(layer, type) %>% filter(services_to != "None" , hop == 0 | hop ==1) %>% 
   mutate(Total = n()) %>% group_by(layer,type, node_id) %>% 
   summarize( Number = n(), Prop = Number /Total) %>% unique()
 
 
 sps_imp_tot_1<- Final_ES %>% group_by(type) %>% filter(services_to != "None", hop == 0 | hop== 1) %>% 
   mutate(Total = n()) %>% group_by(type, node_id) %>% 
   summarize( layer= "Tot",Number = n(), Prop = Number /Total) %>% unique()
 sps_imp_tot_1<-sps_imp_tot_1[,c(3,1,2,4,5)]
 
 sps_imp_tot_ES_1<-rbind(sps_imp_tot_1,sps_imp_1) %>% group_by(layer,node_id) %>% 
   summarize(Tot = sum(Number)) #considering both direct and indirect
 
 
 
 #Just Total (without considering habitats)
 sps_imp_number_1<- sps_imp_tot_ES_1 %>% filter(layer == "Tot") %>%
   ggplot(aes(y=Tot, x= node_id)) + geom_bar(stat="identity")+
   labs(x='Node_id', y="Number of ES provided") +theme_bw()+
   theme_classic()+
   theme(panel.grid = element_blank(),
         panel.border = element_rect(color = "black",fill = NA,size = 1),
         panel.spacing = unit(0.5, "cm", data = NULL),
         axis.text = element_text(size=15, color='black'),
         axis.text.x= element_text(size =13, angle = 90), 
         axis.title = element_text(size=17, color='black'),
         axis.line = element_blank(),
         legend.text.align = 0,
         legend.title =  element_text(size = 13, color = "black"),
         legend.text = element_text(size = 11))
 
 sps_imp_number_1
 
 #chose the four species that provide ecosystem services the most
 
 four_sp_1<-sps_imp_tot_ES_1 %>% filter(layer == "Tot") %>% 
   arrange(desc(Tot)) %>% head(n = 4)
 
 four_sp_birds_1<-sps_imp_tot_ES_1 %>% filter(layer != "Tot", node_id == 41 | node_id == 24 |
                                            node_id == 26 | node_id ==13) 
 four_sp_birds_1$node_id<-as.character(four_sp_birds_1$node_id)
 
 #Most important nodes across habitat
 
 imp_sps_ES_1<- four_sp_birds_1 %>%
   ggplot(aes(y=Tot, x= node_id, fill = layer)) + geom_bar(position="dodge", stat="identity")+
   labs(x='Node_id', y="Number of ES provided") +theme_bw()+
   theme_classic()+
   theme(panel.grid = element_blank(),
         panel.border = element_rect(color = "black",fill = NA,size = 1),
         panel.spacing = unit(0.5, "cm", data = NULL),
         axis.text = element_text(size=15, color='black'),
         axis.text.x= element_text(size =13, angle = 90), 
         axis.title = element_text(size=17, color='black'),
         axis.line = element_blank(),
         legend.text.align = 0,
         legend.title =  element_text(size = 13, color = "black"),
         legend.text = element_text(size = 11))
 
 imp_sps_ES_1
 
 
 